### ISSUE TITLE
Unable to create image with python-start@0.13.0 and buildpack API 0.8

### ISSUE THREAD

**Issue by SamuelYvon** [paketo-buildpacks/python-start#210]
Hi! Using `kn func create -l python` to create a python knative func. Building our image we
get the following error message:

```shell
[restorer] ERROR: failed to : set API for buildpack 'paketo-buildpacks/python-start@0.13.0': buildpack API version '0.8' is incompatible with the lifecycle
Error: executing lifecycle. This may be the result of using an untrusted builder: failed with status code: 12
Error: exit status 1
```

## Expected Behavior

I expected status 0 :( 

## Current Behavior

Error: exit status 1

## Steps to Reproduce

Here is the `func.yaml` we are using

```yaml
specVersion: 0.25.0
name: test
namespace: ""
runtime: python
registry: ""
image: test_image
imageDigest: ""
build: local
git: {}
builderImages:
  pack: paketobuildpacks/builder:full
buildpacks: []
builder: pack
volumes: []
buildEnvs:
- name: BP_CPYTHON_VERSION
  value: "3.9"
envs: []
annotations: {}
options: {}
labels: []
healthEndpoints:
  liveness: /health/liveness
  readiness: /health/readiness
created: 2022-11-02T14:11:48.253105027-04:00
invocation:
  format: cloudevent

```

## Motivations

This prevents us from deploying cloud events functions using python
